logging:
  pattern:
    console: -%clr(%d{${LOG_DATEFORMAT_PATTERN:yyMMdd_HHmmss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%5.5t]){faint} %clr(%-20.20logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
  file:
    name: ./log/my.log
spring:
  output:
    ansi:
      enabled: always